In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch  # Package name: torch (for pip), pytorch (for conda)
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data

In [10]:
# test if
# if g_i > mean_g_i
g = torch.rand(4)
print(g)

mean_g = torch.rand(4)
print(mean_g)

g_new = torch.rand(4)
print(g_new)

torch.where(g > mean_g, g, g_new)

tensor([0.4552, 0.4165, 0.0475, 0.8621])
tensor([0.6074, 0.1316, 0.2362, 0.1088])
tensor([0.7016, 0.3643, 0.1444, 0.4733])


tensor([0.7016, 0.4165, 0.1444, 0.8621])

$\theta^{(j)} = \theta^{(j-1)} + \alpha^{(j)} d^{(j)}, j\in\{1,...,n\}$

$d^{(k)} = - \nabla_{\theta}f(\theta^{(k)})$

## $\alpha$